orangepi:
    hosts:
        loud-orangepi-01:
            ansible_host: 192.168.1.54
        # orange-one-02:
        #     ansible_host: 10.42.0.141
    vars:
        ansible_user: pi
        #  if you're not using ssh-key auth, provide password below
        # ansible_ssh_pass: orangepi
        kernel_header_package: linux-headers-current-sunxi
        raspi_pkg: https://dtcooper.github.io/raspotify/raspotify-latest_armhf.deb
        config_path: /boot/armbianEnv.txt