- name: Librespot
  hosts: AudioEndNodes
  become: yes
  tasks:

  - name: apt install packages
    apt:
      name: 
        - libc6 
        - coreutils 
        - systemd 
        - init-system-helpers 
        - libasound2 
        - alsa-utils 
        - libpulse0
      state: present

  - name: Check if raspotify is installed
    command: dpkg-query -W raspotify
    register: my_package_check_deb
    failed_when: my_package_check_deb.rc > 1
    changed_when: my_package_check_deb.rc == 1

  - name: Download raspotify
    get_url: 
      url="https://dtcooper.github.io/raspotify/raspotify-latest_armhf.deb"
      dest="/tmp/raspotify-latest_armhf.deb"
    when: my_package_check_deb.rc == 1

  - name: Install raspotify
    run_once: yes
    ansible.builtin.shell:
      cmd: dpkg --ignore-depends=coreutils --ignore-depends=alsa-utils --ignore-depends=systemd --ignore-depends=init-system-helpers --ignore-depends=libasound2 -i /tmp/raspotify-latest_armhf.deb
    when: my_package_check_deb.rc == 1
