orange-pi:
    hosts:
        # orange-pi-pc:
        #     ansible_host: 192.168.1.48
        # orange-pi-one:
        #     ansible_host: 192.168.1.84
        loud-orange-pi-01:
            ansible_host: 10.42.0.187
            ansible_user: dronische